- name: Backup of {{ config_path }}
  copy:
    src: "{{ config_path }}"
    dest: "{{ config_path }}.armor-{{ ansible_date_time.iso8601_basic_short }}"
  register: backup_path

- import_tasks: headers.yml

- import_tasks: directives.yml

- import_tasks: modsecurity.yml
  when: set_custom_signature

- name: Checking if change were made
  shell: diff {{ config_path | quote }} {{ backup_path.dest | quote }}
  register: nodiff

- name: Keeping backup
  debug:
    msg: Backup file is at {{ backup_path.dest }}
  when: nodiff is fail

- name: Deleting backup
  file:
    path: "{{ backup_path.dest }}"
    state: absent
  when: nodiff is success
