- name: Install modsecurity module
  package:
    name:
      - libapache2-mod-security2
    state: latest

- name: Enable headers module
  apache2_module:
      name: "{{ item }}"
      state: present
  loop:
    - headers
    - security2
  notify: restart apache

- name: ServerTokens Prod
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^ServerTokens .*
    line: ServerTokens Prod
  notify: restart apache

- name: ServerSignature Off
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^ServerSignature .*
    line: ServerSignature Off
  notify: restart apache

- name: FileETag None
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^FileETag .*
    line: FileETag None
  notify: restart apache

- name: Timeout {{ timeout_value }}
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^Timeout .*
    line: Timeout {{ timeout_value }}
  notify: restart apache

- name: TraceEnable off
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^TraceEnable .*
    line: TraceEnable off
  notify: restart apache

- name: Header set X-Frame-Options sameorigin
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: Header .* X-Frame-Options
    line: Header set X-Frame-Options sameorigin
  notify: restart apache

- name: Header set X-XSS-Protection "1; mode=block"
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: Header .* X-XSS-Protection
    line: Header set X-XSS-Protection "1; mode=block"
  notify: restart apache

- name: Header set X-Content-Type-Options nosniff
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: Header .* X-Content-Type-Options
    line: Header set X-Content-Type-Options nosniff
  notify: restart apache

- name: Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: Header .* Set-Cookie
    line: Header always edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
  notify: restart apache

- import_tasks: modsecurity
- import_tasks: headers
- import_tasks: directives
