- name: Creating temporary copy {{ temp_file | basename }} of {{ config_file | basename }}
  copy:
    src: "{{ config_file }}"
    dest: "{{ temp_file }}"

- import_tasks: headers.yml

- import_tasks: directives.yml

- import_tasks: modsecurity.yml
  when: set_custom_signature

- name: Overwriting {{ config_file }}
  copy:
    src: "{{ temp_file }}"
    dest: "{{ config_file }}"
    backup: yes

- name: Deleting temporary copy {{ temp_file }}
  file:
    path: "{{ temp_file }}"
    state: absent
