- name: Install security module
  package:
    name:
      - libapache2-mod-security2
    state: latest

- name: Enable security2 module
  apache2_module:
    name: security2
    state: present
  notify: restart apache

- name: SecServerSignature
