- name: Install security module
  package:
    name:
      - "{{ mod_security_package_name }}"
    state: latest

- name: Enable security module
  apache2_module:
    name: "{{ security_module_name }}"
    state: present
  notify: restart apache

- name: SecServerSignature
